apiVersion: v2
name: mealie
description: Mealie is a self hosted recipe manager and meal planner with a RestAPI backend and a reactive frontend application built in Vue for a pleasant user experience for the whole family.
version: 1.1.5
appVersion: "v3.5.0"
kubeVersion: ">=1.16.0-0" #Optional, but good to indicate minimum Kubernetes version
keywords:
  - mealie
sources:
  - https://github.com/mealie-recipes/mealie
dependencies:
  - name: postgresql
    version:  16.7.5 #This is a chart version, not app version.
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
maintainers:
  - name: Douwe Meulenbroek
    # email: your-email@example.com    